version: '3'

services:
  app:
    build: .
    # this shellscript command execution 
    # will overwrite CMD from Dockerfile image
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app